color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.2265236412640661
  lightness: 0.17650209041312337
  saturation: 0.3287152932025492
  rhythmicContrast: 0.5967214012052864
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Vulcano
layout_spectrum: 0.9717858317308128
typography_spectrum: 0.2906853777822107
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1cac0cc-0818-417c-b5a9-1f03f76b92ea.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1cac0cc-0818-417c-b5a9-1f03f76b92ea.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Entertaints
description: Music publiser
github: true
author:
  name: Purnomo Adhari
  email: praboe6@gmail.com
